// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQU4D.Data.Context;

#nullable disable

namespace SQU4D.Migrations
{
    [DbContext(typeof(Squ4dContext))]
    [Migration("20231017215656_arrumandoTabelaVeiculo")]
    partial class arrumandoTabelaVeiculo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SQU4D.Data.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgementStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AlertApiId")
                        .HasColumnType("int");

                    b.Property<int?>("Bus")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefinitionBus")
                        .HasColumnType("int");

                    b.Property<string>("DefinitionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionFailureModeIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("DefinitionLinkRel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionLinkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionLinkUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionSourceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionSuspectParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionThreeLetterAcronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DurationValue")
                        .HasColumnType("float");

                    b.Property<string>("EngineHoursType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineHoursUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EngineHoursValue")
                        .HasColumnType("float");

                    b.Property<bool>("Ignored")
                        .HasColumnType("bit");

                    b.Property<bool>("Invisible")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("LinkRel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<int>("MachineLinearTime")
                        .HasColumnType("int");

                    b.Property<string>("Occurrences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.Property<string>("VeiculoId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId1");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Encaminhamento", b =>
                {
                    b.Property<int>("IdEncaminhamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEncaminhamento"));

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("EncaminhamentoAtivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrigemRetorno")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEncaminhamento");

                    b.HasIndex("AlertId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Encaminhamento");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Veiculo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Alert", b =>
                {
                    b.HasOne("SQU4D.Data.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId1");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Encaminhamento", b =>
                {
                    b.HasOne("SQU4D.Data.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQU4D.Data.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SQU4D.Data.Models.Veiculo", b =>
                {
                    b.HasOne("SQU4D.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
